spring:
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

  datasource:
    sql-script-encoding: UTF-8
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug