spring:
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
#  datasource:
#    url: "jdbc:h2:file:~/spring-boot-h2-db"
#    driver-class-name: "org.h2.Driver"
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug